const types = {
  FETCH_IMAGES: "FETCH_IMAGES",
  FETCHING_IMAGES: "FETCHING_IMAGES",
  FETCHING_IMAGES_FINISHED: "FETCHING_IMAGES_FINISHED",
  UPDATE_PAGINATION_COUNT: "UPDATE_PAGINATION_COUNT",
  UPLOAD_IMAGE: "UPLOAD_IMAGE",
  UPLOAD_RESET: "UPLOAD_RESET",
  UPLOADING_PENDING: "UPLOADING_PENDING",
  UPLOAD_IMAGE_FINISHED: "UPLOAD_IMAGE_FINISHED",
  SHOW_ERROR: "SHOW_ERROR",
  CLEAN_ERROR: "CLEAN_ERROR",
  FETCH_ALL_FAVOURITES_FINISHED: "FETCH_ALL_FAVOURITES_FINISHED",
  ADD_FAVOURITE: "ADD_FAVOURITE",
  REMOVE_FAVOURITE: "REMOVE_FAVOURITE",
  UPDATE_SCORE: "UPDATE_SCORE",
  GET_SCORES: "GET_SCORES",
}

export default types;