const types = {
  FETCH_IMAGES: "FETCH_IMAGES",
  FETCHING_IMAGES: "FETCHING_IMAGES",
  FETCHING_IMAGES_FINISHED: "FETCHING_IMAGES_FINISHED",
  UPLOAD_IMAGE: "UPLOAD_IMAGE",
  UPLOADING_PENDING: "UPLOADING_PENDING",
  UPLOAD_IMAGE_FINISHED: "UPLOAD_IMAGE_FINISHED",
  ERROR_OCCURRED: "ERROR_OCCURRED"
}

export default types;