const types = {
  FETCH_IMAGES: "FETCHING_IMAGES",
  FETCHING_IMAGES: "FETCHING_IMAGES",
  FETCHING_IMAGES_FINISHED: "FETCHING_IMAGES_FINISHED",
  UPLOAD_IMAGE: "UPLOAD_IMAGE",
  UPLOAD_IMAGE_FINISHED: "UPLOAD_IMAGE_FINISHED"
}

export default types;